apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-deployment 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-svc
  template:
    metadata:
      labels:
        app: student-svc
    spec:
      containers:
        - name: student-svc
          image: eranga4u/demo:0.0.2-SNAPSHOT
          ports:
            - containerPort: 8081
          livenessProbe:
            httpGet:
               path: /health
               port: 8081   
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/demo
          imagePullPolicy: Always
